name: Build, Release & Publish

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  release:
    name: Build, Release, & Publish Plugin
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required for pushing tags back

      - name: Setup NodeJS
        uses: actions/setup-node@v6
        with:
          node-version: '24'
          registry-url: 'https://registry.npmjs.org'



      - name: Install Dependencies
        run: npm ci

      - name: Build Plugin
        run: npm run build



      - name: Pack Plugin
        id: pack
        run: |
          # Generate the .tgz file
          TARBALL=$(npm pack)
          echo "tarball=$TARBALL" >> $GITHUB_OUTPUT



      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          files: ${{ steps.pack.outputs.tarball }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to NPM
        run: npm publish --provenance --access public
